accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "accounts"

urlpatterns = [

    path('login/', views.login_view, name="login"),
    path('login/<str:from_password_reset>/', views.login_view2, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('update_user/', views.update_user_view, name="update-user"),
    path('profile/<str:pk>/', views.profile_view, name="profile"),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/',views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

api/urls.py
from django.urls import path, include
from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Francium API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
   path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   # path('', views.getRoutes),
   path('rooms/', views.RoomListView.as_view()),
   path('rooms/<str:pk>/', views.GetRoomView.as_view()),
   path('create_room/', views.CreateRoomView.as_view()),
   path('room_msgs/<str:pk>/', views.GetMessagesByRoom.as_view()),
   path('send_message/<str:pk>/', views.CreateMessage.as_view()),
   path('room_request/', views.CreateRoomRequest.as_view()),
   path('room_requests/<str:pk>/', views.RoomRequestsView.as_view()),
   path('manage_room_requests/<str:pk>/', views.ManageRoomRequest),
   path('topics/', views.TopicView.as_view()),

   path('accounts/', include('api.accounts.urls')),
]

francium/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

studybud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import AbstractUser
from base.resize_image import ResizeImageMixin
# Create your models here.
class User(AbstractUser, ResizeImageMixin):
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(unique=True, null = True)
    bio = models.TextField(null=True, blank=True)
    avatar = models.ImageField(null=True,upload_to="profile_pics/", default='avatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def save(self, *args, **kwargs):
        if self.avatar:
            self.resize(self.avatar, (300, 300))
        super().save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from django.forms import ModelForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('name','username', 'email', 'password1', 'password2',)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = '__all__'

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'avatar', 'name', 'bio',]

accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import User
from base.models import Topic
from django.db.models import Q
from django.contrib import messages
from .forms import CustomUserChangeForm, CustomUserCreationForm, UserForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.core.paginator import Paginator
# Create your views here.


def login_view(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if(request.method == 'POST'):
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        
        try:
            temp_user = User.objects.get(email=email)
        except:
            messages.error(request, "User does not exists")
            return render(request, 'accounts/login_register.html', {})    
            
        
        user = authenticate(request, email = email, password = password)
        if(user is not None):
            login(request, user)
            messages.success(request, "Login success")
            return redirect('base:home')
        else:
            messages.error(request, "username and password does not match")

    context = {'page':page}
    return render(request, 'accounts/login_register.html', context)

def login_view2(request, from_password_reset):
    from_login = request.GET.get('from_password_reset') if request.GET.get('from_password_reset') != None else 0
    auth_tagline = ""
    if(from_login):
        auth_tagline = "Your password has been set.  You may go ahead and log in now."
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if(request.method == 'POST'):
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        
        try:
            temp_user = User.objects.get(email=email)
        except:
            messages.error(request, "User does not exists")
            return render(request, 'accounts/login_register.html', {})    
            
        
        user = authenticate(request, email = email, password = password)
        if(user is not None):
            login(request, user)
            messages.success(request, "Login success")
            return redirect('base:home')
        else:
            messages.error(request, "username and password does not match")

    context = {'page':page, 'auth__tagline': auth_tagline}
    return render(request, 'accounts/login_register.html', context)


def logout_view(request):
    logout(request)
    messages.info(request, "Logout success")
    return redirect('base:home')

def register_view(request):
    if request.user.is_authenticated:
        return redirect('base:home')
    page = 'register'
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if(form.is_valid()):
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.email = user.email.lower()
            user.save()
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, form.errors)


    context = {'page':page, 'form':form}
    return render(request, 'accounts/login_register.html', context)


@login_required
def update_user_view(request):
    if(request.method == 'POST'):
        form = UserForm(request.POST,request.FILES,  instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user.id)
        else:
            messages.warning(request, form.errors)

    user = request.user
    form = UserForm(instance=user)
    context = {'form':form, 'user':user}

    return render(request, 'accounts/update_user.html', context)

def profile_view(request, pk):
    user = get_object_or_404(User, id=pk)
    if(request.user.id == int(pk)):
        rooms = user.room_set.all()
    else:
        rooms = user.room_set.filter(is_private=False)
    topics_count = Topic.objects.count()
    room_messages = user.message_set.filter(Q(room__is_private=False))[:5]
    topics = Topic.objects.all()[:5]
    context = {'user':user,'rooms':rooms, 'room_messages':room_messages, 'topics':topics, 'topics_count' : topics_count}
    return render(request, 'accounts/profile.html', context)


class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'accounts/password_reset_email.html'
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'
    pass

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    post_reset_login = True
    success_url = reverse_lazy('accounts:login', kwargs={'from_password_reset':1})

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

api/accounts/views.py
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from .serializers import RegisterUserSerializer, SetNewPasswordSerializer, UserSerializer, PasswordUpdateSerializer, PasswordResetSerializer
from django.contrib.auth.hashers import make_password
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.models import AnonymousUser
from rest_framework import status
from django.contrib.auth import get_user_model
from rest_framework import generics
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import smart_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from drf_yasg.utils import swagger_auto_schema


User = get_user_model()
class CustomAuthToken(ObtainAuthToken):
    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data, context={'request':request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token , created = Token.objects.get_or_create(user = user)
        data = {}
        data['username'] = user.username
        data['user_id'] = user.id
        data['token'] = token.key
        data['email'] = user.email
        return Response(data)

@swagger_auto_schema(method='post', request_body=RegisterUserSerializer)
@api_view(['POST', ])
def registerUserView(request):
    if request.method == "POST":
        serializer = RegisterUserSerializer(data=request.data)
        data = {}
        if(serializer.is_valid()):
            passwd = serializer.validated_data.get('password')
            serializer.validated_data['password'] = make_password(passwd)
            user = serializer.save()
            data['username'] = user.username
            data['email'] = user.email
            token = Token.objects.get(user = user)
            data['token'] = token.key
            return Response(data)
        else:
            data = serializer.errors
        return Response(data)

    
@swagger_auto_schema(method='put', request_body=UserSerializer)
@api_view(['PUT',])
@permission_classes([IsAuthenticated, ])
def UserUpdateView(request, *args, **kwargs):
    if request.method == 'PUT':
        print(request.user)
        serializer = UserSerializer(request.user ,data = request.data, partial=True)
        if(serializer.is_valid()):
            user = serializer.save()
            data = {}
            data['message'] = "user details updated"
            data['data'] = serializer.data
            return Response(data, status=status.HTTP_202_ACCEPTED)
        else:
            return Response({'errors':serializer.errors, 'detail':"fields not updated"}, status=status.HTTP_304_NOT_MODIFIED)

class UserDetailsView(generics.RetrieveAPIView):
    queryset = User.objects.all()
    lookup_field = "pk"
    serializer_class = UserSerializer

class UserPasswordChangeView(generics.UpdateAPIView):
    serializer_class = PasswordUpdateSerializer
    permission_classes = [IsAuthenticated, ]

    def update(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if(serializer.is_valid()):
            user = serializer.save()
            if(hasattr(user, 'auth_token')):
                user.auth_token.delete()
            token, created = Token.objects.get_or_create(user=user)
            return Response({'token':token.key}, status=status.HTTP_202_ACCEPTED)
        else:
            return Response(serializer.errors, status=status.HTTP_406_NOT_ACCEPTABLE)

class RequestPasswordResetEmail(generics.GenericAPIView):
    serializer_class = PasswordResetSerializer
    def post(self, request):
        serializer = self.get_serializer(data = request.data)
        serializer.is_valid(raise_exception=True)
        return Response({'detail':"A mail with password reset instructions has been sent to your email address."}, status=status.HTTP_200_OK)


@api_view(['GET',])
def PasswordTokenCheckView(self, request, uidb64, token, **kwargs):
    if request.method == 'POST':
        try:
            id = smart_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(id = id)
        except:
            return Response({'detail':"please enter a valid url or try to reset the password after sometime"})
        if not PasswordResetTokenGenerator().check_token(user = user, token=token):
            return Response({'detail':"Password reset process failed please generate a new token"}, status=status.HTTP_400_BAD_REQUEST)
        
        return Response({'detail':"Password reset token verification success", 'token':token, 'uidb64':uidb64}, status=status.HTTP_200_OK)

class SetNewPassword(generics.GenericAPIView):
    serializer_class = SetNewPasswordSerializer
    
    def patch(self, request):
        serializer = self.get_serializer(data=request.data)
        if(serializer.is_valid()):
            serializer.save()
            return Response({'detail':"password reset successfully completed"}, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

accounts/templates/accounts/login_register.html
{%  extends 'base.html'  %}
{% block body %}
{%  if page == 'login'  %}


    
<main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Login</h3>
          </div>
        </div>
        <div class="layout__body">
          <h2 class="auth__tagline">{{  auth__tagline  }}</h2>

          <form class="form" method="POST">
              {%  csrf_token  %}
            <div class="form__group form__group">
              <label for="email">Email</label>
              <input autofocus autocomplete="off" spellcheck="false" id="email" name="email" type="email" placeholder="Enter Your Email.." />
            </div>
            <div class="form__group">
              <label for="password">Password</label>
              <input autocomplete="off" id="password" name="password" type="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
            </div>

            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>

              Login
            </button>
            <a class="forgot_password_link" href="{%  url 'accounts:password_reset'  %}">Forgot Password?</a>
          </form>

          <div class="auth__action">
            <p>Haven't signed up yet?</p>
            <a href="{%  url 'accounts:register'  %}" class="btn btn--link">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </main>
{%  endif  %}
{%  if page == 'register'  %}

<main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Sign up</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" method="post" action="">
            {%  csrf_token  %}
            {%  for field in form  %}
                <div class="form__group">
                    <label for="fullname">{{  field.label  }}</label>
                    {{  field  }}
                </div>
            {%  endfor  %}
            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>
              Sign Up
            </button>
          </form>

          <div class="auth__action">
            <p>Already have an account?</p>
            <a href="{%  url 'accounts:login'  %}" class="btn btn--link">Log In</a>
          </div>
        </div>
      </div>
    </div>
  </main>
{%  endif  %}
{% endblock body %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block body %}

<main >
    <div class="password_reset_done">
        <p>Your password has been set.  You may go ahead and log in now.</p>
        <p><a href="{{ login_url }}">Log in</a></p>
    </div>
</main>
{% endblock body %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block body %}
    

{% if validlink %}
<main class="auth layout">
<div class="container">
  <div class="layout__box">
    <div class="layout__boxHeader">
      <div class="layout__boxTitle">
        <h3>Change Password</h3>
      </div>
    </div>
    <div class="layout__body">
      <h2 class="auth__tagline">Please enter your new password twice so we can verify you typed it in correctly.</h2>
      
      <form class="form" method="POST">
          {%  csrf_token  %}
          <input hidden class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
        <div class="form__group">
            {{ form.new_password1.errors }}
            <label for="id_new_password1">New password:</label>
            {{ form.new_password1 }}
        </div>
        <div class="form__group">
            {{ form.new_password2.errors }}
            <label for="id_new_password2">Confirm password:</label>
            {{ form.new_password2 }}
        </div>
        <button class="btn btn--main" type="submit">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>lock</title>
            <path
              d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
            ></path>
            <path
              d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
            ></path>
          </svg>

          Change password
        </button>
      </form>

      <!-- <div class="auth__action">
        <p>Haven't signed up yet?</p>
        <a href="{%  url 'accounts:register'  %}" class="btn btn--link">Sign Up</a>
      </div> -->
    </div>
  </div>
</div>
</main>

{% else %}

<main >
    <div class="password_reset_done">
      <p>
        The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.
      </p>
    </div>
</main>

{% endif %}
{% endblock body %} 

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block body %}

<main >
    <div class="password_reset_done">
        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
        <br>
        <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
        </div>
    </div>
</main>

{% endblock body %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% block body %}
<main class="auth layout">
    <div class="container">
      <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <h3>Reset Password</h3>
                </div>
            </div>
            <div class="layout__body">
                <h2 class="auth__tagline">Please enter your email address to send password reset instructions</h2>

                <form class="form" method="POST">
                    {%  csrf_token  %}
                    {{ form.email.errors }}
                    <div class="form__group form__group">
                        <label for="id_email">Email</label>
                        {{ form.email }}
                    </div>

                <button class="btn btn--main" type="submit">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>lock</title>
                        <path d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
                        </path>
                        <path d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
                        </path>
                    </svg>

                    Reset
                </button>
                </form>

                <div class="auth__action">
                    <!-- <p>Login</p> -->
                    <a href="{%  url 'accounts:login'  %}" class="btn btn--link">Login</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock body %}

accounts/templates/accounts/profile.html
{%  extends 'base.html'  %}

{% block body %}
<main class="profile-page layout layout--3">
    <div class="container">

        <div class="topics">
            {%  include 'base/topics_component.html'  %}
        </div>
        <div class="roomList">
            <div class="mobile-menu">
                <form class="header__search">
                  <label>
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>search</title>
                      <path
                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                      ></path>
                    </svg>
                    <input placeholder="Search for posts" />
                  </label>
                </form>
                <div class="mobile-menuItems">
                  <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
                  <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
                </div>
              </div>
            <div class="profile">
              <div class="profile__avatar">
                <div class="avatar avatar--large active">
                  <img src="{{  user.avatar.url  }}" />
                </div>
              </div>
              <div class="profile__info">
                <h3>{{ user.username }}</h3>
                <p>@{{  user.username  }}</p>
                {%  if user == request.user  %}
                <a href="{%  url 'accounts:update-user'  %}" class="btn btn--main btn--pill">Edit Profile</a>
                {%  endif  %}
              </div>
              <div class="profile__about">
                <h3>About</h3>
                <p>
                  {{  user.bio  }}
                </p>
              </div>
            </div>
            {%  include 'base/feed_component.html'  %}   

        </div>
        <div class="activities">
            {%  include 'base/activity_component.html'  %}
        </div>    
    </div>
</main>

{% endblock body %}

accounts/templates/accounts/update_user.html
{%  extends 'base.html'  %}
{%  load static  %}
{% block extra_head %}
{% endblock extra_head %}

{% block body %}
<main class="update-account layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{% url 'accounts:profile' request.user.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Edit your profile</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" enctype="multipart/form-data">
                    {%  csrf_token  %}

                    {%  for field in form  %}
                    <div class="form__group">
                        <label>{{field.label}}</label>
                        {{  field  }}
                    </div>
                    {%  endfor  %}
                    <div class="form__action">
                        <a class="btn btn--dark" href="{{  request.META.HTTP_REFERER  }}">Cancel</a>
                        <button class="btn btn--main" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </div>
</main>
<script src="{%  static 'js/resizer.js'  %}"></script>

{% endblock body %}