accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "accounts"

urlpatterns = [

    path('login/', views.login_view, name="login"),
    path('login/<str:from_password_reset>/', views.login_view2, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('update_user/', views.update_user_view, name="update-user"),
    path('profile/<str:pk>/', views.profile_view, name="profile"),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/',views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

api/urls.py
from django.urls import path, include
from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Francium API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
   path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   # path('', views.getRoutes),
   path('rooms/', views.RoomListView.as_view()),
   path('rooms/<str:pk>/', views.GetRoomView.as_view()),
   path('create_room/', views.CreateRoomView.as_view()),
   path('room_msgs/<str:pk>/', views.GetMessagesByRoom.as_view()),
   path('send_message/<str:pk>/', views.CreateMessage.as_view()),
   path('room_request/', views.CreateRoomRequest.as_view()),
   path('room_requests/<str:pk>/', views.RoomRequestsView.as_view()),
   path('manage_room_requests/<str:pk>/', views.ManageRoomRequest),
   path('topics/', views.TopicView.as_view()),

   path('accounts/', include('api.accounts.urls')),
]

base/urls.py
from django.urls import path
from . import views
app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create_room/', views.create_room, name="create-room"),
    path('update_room/<str:pk>/', views.update_room, name='update-room'),
    path('delete_room/<str:pk>/', views.delete_room, name='delete-room'),
    path('delete_message/<str:pk>/', views.delete_message, name='delete-message'),
    path('topics/', views.topics_view, name="topics"),
    path('activity/', views.activity_view, name="activity"),
    path('room_requests/<str:room_id>/', views.room_requests, name="requests"),
]

francium/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

studybud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from base.resize_image import ResizeImageMixin

# Create your models here.

User = get_user_model()

class Topic(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, unique=True)

    def __str__(self) -> str:
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated', '-created']
        
    def __str__(self) -> str:
        return self.name

class Message(models.Model, ResizeImageMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    isImage = models.BooleanField(default=False)
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    message_image = models.ImageField(default="messages/default.jpg", upload_to="messages/", null=True, blank=True)

    def __str__(self) -> str:
        if(len(self.body) > 50):
            return self.body[0:50]
        return self.body

    class Meta:
        ordering = ['-updated', '-created']


class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    request_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-request_time', 'room']
        verbose_name = 'Join request'
    
    def __str__(self) -> str:
        return self.user.username + " requested to join " + self.room.name

    

base/forms.py
from dataclasses import fields
from django.forms import ModelForm
from django import forms
from .models import Room, Message
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']



class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['body', 'message_image']

base/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import  get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from base.models import Request, Room, Topic , Message
from base.forms import MessageForm, RoomForm
from api.custom_validators import check_empty

# Create your views here.

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    rooms = Room.objects.filter(
                Q(topic__name__icontains = q) | 
                Q(name__icontains = q)|
                Q(description__icontains = q)
            ).order_by("-updated")
    room_count = rooms.count()
    paginator = Paginator(rooms, 2)
    page_number = request.GET.get('page')
    rooms = paginator.get_page(page_number)
    room_messages = Message.objects.filter(Q(room__topic__name__icontains = q) & Q(room__is_private=False))[:5]
    topics_count = Topic.objects.count()
    topics = Topic.objects.all()[:5]
    context = {'rooms':rooms, 'topics':topics, 'room_count':room_count, 'room_messages':room_messages, 'topics_count':topics_count}
    # messages.info(request, "show some info message")
    return render(request, 'base/home.html', context)


def about(request):
    return render(request, 'base/about.html')

def room(request, pk):
    room = get_object_or_404(Room, id=pk)
    if(room.is_private == False or room.participants.filter(id=request.user.id).exists()):
        form = MessageForm()
        if(request.method == 'POST'):
            body = request.POST.get('msg_body')
            form = MessageForm(request.POST, request.FILES)
            if(form.is_valid() and (not check_empty(body) or request.FILES.get('message_image') is not None)):
                message = form.save(commit=False)
                if(message.message_image != "messages/default.jpg"):
                    message.isImage = True
                    message.body = message.message_image.name
                else:
                    message.isImage = False
                    message.body = body
                message.user = request.user
                message.room = room
                message.save()
                room.participants.add(request.user)
                return redirect('base:room', pk=room.id)
            else:
                messages.error(request, form.errors)

        room_messages = room.message_set.all().order_by('-created')[:10][::-1]
        participants = room.participants.all()
        context = {'has_access':True, 'room':room, 'msgs':room_messages, 'participants':participants, 'form':form}
        return render(request, 'base/room.html', context)
    else:
        if not request.user.is_authenticated:
            messages.info(request, "This room is private you must login to view this")
            return redirect("accounts:login")

        if(request.method == "POST"):
            req , created = Request.objects.get_or_create(
                user = request.user,
                room = room,
            )
        requested = Request.objects.filter(user=request.user, room=room)
        if(requested.exists()):
            requested = True
        else:
            requested = False
        context = {"has_access":False, 'room':room, 'requested':requested}
        return render(request, 'base/room.html', context)

@login_required
def create_room(request):
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room = Room.objects.create(
            host = request.user,
            topic = topic,
            name=request.POST.get('name'),
            description = request.POST.get('description')
        )
        if(request.POST.get('is_private') == 'on'):
            room.is_private = True
        room.save()
        room.participants.add(request.user)
        return redirect('base:home')

    form = RoomForm()
    topics = Topic.objects.all()
    context = {'form': form, 'topics':topics}
    return render(request, 'base/forms/room.html', context)

def update_room(request, pk):
    room = get_object_or_404(Room, id = pk)
    if(request.user != room.host):
        return HttpResponse("Your are not allowed here!")

    form = RoomForm(instance=room)
    if(request.method == 'POST'):
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        room.topic = topic
        if(request.POST.get('is_private') == 'on'):
            room.is_private = True
        room.save()
        return redirect('base:home')
    topics = Topic.objects.all()
    
    context = {'form':form, 'topics':topics, 'room':room}

    return render(request, 'base/forms/room.html', context)    


def delete_room(request, pk):
    room = get_object_or_404(Room, id=pk)
    if(request.user != room.host):
        return HttpResponse("Your are not allowed here!")
    if(request.method == 'POST'):
        room.delete()
        return redirect('base:home')
    
    context = {'obj' :room}
    return render(request, 'base/forms/delete.html',context)


@login_required
def delete_message(request, pk):
    msg = get_object_or_404(Message, id=pk)
    if(request.user  != msg.user):
        return HttpResponse("Your are not allowed here!")
    if(request.method == 'POST'):
        msg.delete()
        return redirect('base:home')
    return render(request, 'base/forms/delete.html', {'obj':msg})



def topics_view(request):


    q = request.GET.get('q') if request.GET.get('q') != None else ""
    topics = Topic.objects.filter(name__icontains = q)
    context = {'topics':topics}

    return render(request, 'base/topics.html', context)


def activity_view(request):
    room_messages = Message.objects.filter(Q(room__is_private=False))
    paginator = Paginator(room_messages, 5)
    page_number = request.GET.get('page')
    room_messages = paginator.get_page(page_number)
    context = {'room_messages':room_messages}
    
    return render(request, 'base/activity.html', context)

def room_requests(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if(room.host != request.user):
        return HttpResponse("You are not Allowed Here")
    

    join_requests = room.request_set.all()
    if request.method == 'POST':
        for req in join_requests:
            if(request.POST.get(req.user.username) == 'Accept'):
                room.participants.add(req.user)
                req.delete()
            elif(request.POST.get(req.user.username) == 'Decline'):
                req.delete()
        return redirect('base:room' , pk=room.id)

    context = {'join_requests':join_requests}
    
    return render(request, 'base/room_requests.html', context)

base/templates/base/forms/delete.html
{%  extends 'base.html'  %}

{% block body %}
    <form action="" method="post">
        {%  csrf_token  %}
        <p>
            Are you sure You want to delete {{  obj  }}
        </p>
        <a href="{{ request.META.HTTP_REFERER }}">Go Back</a>
        <input type="submit" value="Confirm">

    </form>
{% endblock body %}

base/templates/base/forms/login_register.html
{%  extends 'base.html'  %}
{% block body %}
{%  if page == 'login'  %}


    
<main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Login</h3>
          </div>
        </div>
        <div class="layout__body">
          <h2 class="auth__tagline">Find your study partner</h2>

          <form class="form" method="POST">
              {%  csrf_token  %}
            <div class="form__group form__group">
              <label for="email">Email</label>
              <input autofocus autocomplete="off" spellcheck="false" id="email" name="email" type="email" placeholder="Enter Your Email.." />
            </div>
            <div class="form__group">
              <label for="password">Password</label>
              <input autocomplete="off" id="password" name="password" type="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
            </div>

            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>

              Login
            </button>
          </form>

          <div class="auth__action">
            <p>Haven't signed up yet?</p>
            <a href="{%  url 'base:register'  %}" class="btn btn--link">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </main>
{%  endif  %}
{%  if page == 'register'  %}

<main class="auth layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <h3>Sign up</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" method="post" action="">
            {%  csrf_token  %}
            {%  for field in form  %}
                <div class="form__group">
                    <label for="fullname">{{  field.label  }}</label>
                    {{  field  }}
                </div>
            {%  endfor  %}
            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>
              Sign Up
            </button>
          </form>

          <div class="auth__action">
            <p>Already have an account?</p>
            <a href="{%  url 'base:login'  %}" class="btn btn--link">Log In</a>
          </div>
        </div>
      </div>
    </div>
  </main>
{%  endif  %}
{% endblock body %}

base/templates/base/forms/room.html
{%  extends 'base.html'  %}

{% block body %}

  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{%  url 'base:home'  %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create/Update Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" method="POST" action="#">
            {%  csrf_token  %}
            <!-- {%  for field in form  %} -->
            <!-- <div class="form__group">
              <label for="room_name">{{  field.label  }}</label>
              {{  field  }} -->
              <!-- <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" /> -->
            <!-- </div> -->
            
            <!-- {%  endfor  %} -->

            <div class="form__group">
                <label for="room_topic">Topic</label>
                <input name="topic" id="topic" value="{{  room.topic.name  }}" list="topic-list"/>
                <datalist id="topic-list">
                    <select id="room_topic">
                        {%  for topic in topics  %}
                        <option value="{{  topic.name  }}"> {{  topic.name  }} </option>
                        {%  endfor  %}
                    </select>
                </datalist>
            </div>  

            <div class="form__group">
              <label for="id_name">Room Name</label>
              {{  form.name  }}
            </div>
            <div class="form__group">
                <label for="id_description">Room Description</label>
                {{  form.description  }}
            </div>
            <!-- <div class="form__group"> -->
              <div class="is_private_container">
                <label for="id_is_private">Priavte Room</label>
                {{  form.is_private  }}
              </div>

            <!-- <div class="form__group">
              <label for="room_topic">Topic</label>
              <input required type="text" name="topic" id="room_topic" list="topic-list" />
              <datalist id="topic-list">
                <select id="room_topic">
                  <option value="">Select your topic</option>
                  <option value="Python">Python</option>
                  <option value="Django">Django</option>
                </select>
              </datalist>

            </div> -->


            <!-- <div class="form__group">
              <label for="room_about">About</label>
              <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea>
            </div> -->
            <div class="form__action">
              <a class="btn btn--dark" href="{{  request.META.HTTP_REFERER  }}">Cancel</a>
              <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
    <!-- <div class="">
        <form action="" method="post">
            {{  form.as_p  }}
            <input type="submit" value="Submit">
        </form>
    </div> -->
{% endblock body %}

base/templates/base/forms/update_user.html
{%  extends 'base.html'  %}

{% block body %}
<main class="update-account layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{% url 'base:profile' request.user.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Edit your profile</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" enctype="multipart/form-data">
                    {%  csrf_token  %}

                    {%  for field in form  %}
                    <div class="form__group">
                        <label>{{field.label}}</label>
                        {{  field  }}
                    </div>
                    {%  endfor  %}
                    <div class="form__action">
                        <a class="btn btn--dark" href="{{  request.META.HTTP_REFERER  }}">Cancel</a>
                        <button class="btn btn--main" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </div>
</main>
{% endblock body %}