accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "accounts"

urlpatterns = [

    path('login/', views.login_view, name="login"),
    path('login/<str:from_password_reset>/', views.login_view2, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('update_user/', views.update_user_view, name="update-user"),
    path('profile/<str:pk>/', views.profile_view, name="profile"),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/',views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

api/urls.py
from django.urls import path, include
from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Francium API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
   path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   # path('', views.getRoutes),
   path('rooms/', views.RoomListView.as_view()),
   path('rooms/<str:pk>/', views.GetRoomView.as_view()),
   path('create_room/', views.CreateRoomView.as_view()),
   path('room_msgs/<str:pk>/', views.GetMessagesByRoom.as_view()),
   path('send_message/<str:pk>/', views.CreateMessage.as_view()),
   path('room_request/', views.CreateRoomRequest.as_view()),
   path('room_requests/<str:pk>/', views.RoomRequestsView.as_view()),
   path('manage_room_requests/<str:pk>/', views.ManageRoomRequest),
   path('topics/', views.TopicView.as_view()),

   path('accounts/', include('api.accounts.urls')),
]

base/urls.py
from django.urls import path
from . import views
app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create_room/', views.create_room, name="create-room"),
    path('update_room/<str:pk>/', views.update_room, name='update-room'),
    path('delete_room/<str:pk>/', views.delete_room, name='delete-room'),
    path('delete_message/<str:pk>/', views.delete_message, name='delete-message'),
    path('topics/', views.topics_view, name="topics"),
    path('activity/', views.activity_view, name="activity"),
    path('room_requests/<str:room_id>/', views.room_requests, name="requests"),
]

francium/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

studybud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from base.resize_image import ResizeImageMixin

# Create your models here.

User = get_user_model()

class Topic(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, unique=True)

    def __str__(self) -> str:
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated', '-created']
        
    def __str__(self) -> str:
        return self.name

class Message(models.Model, ResizeImageMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    isImage = models.BooleanField(default=False)
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    message_image = models.ImageField(default="messages/default.jpg", upload_to="messages/", null=True, blank=True)

    def __str__(self) -> str:
        if(len(self.body) > 50):
            return self.body[0:50]
        return self.body

    class Meta:
        ordering = ['-updated', '-created']


class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    request_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-request_time', 'room']
        verbose_name = 'Join request'
    
    def __str__(self) -> str:
        return self.user.username + " requested to join " + self.room.name

    

base/forms.py
from dataclasses import fields
from django.forms import ModelForm
from django import forms
from .models import Room, Message
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']



class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['body', 'message_image']

base/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import  get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from base.models import Request, Room, Topic , Message
from base.forms import MessageForm, RoomForm
from api.custom_validators import check_empty

# Create your views here.

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    rooms = Room.objects.filter(
                Q(topic__name__icontains = q) | 
                Q(name__icontains = q)|
                Q(description__icontains = q)
            ).order_by("-updated")
    room_count = rooms.count()
    paginator = Paginator(rooms, 2)
    page_number = request.GET.get('page')
    rooms = paginator.get_page(page_number)
    room_messages = Message.objects.filter(Q(room__topic__name__icontains = q) & Q(room__is_private=False))[:5]
    topics_count = Topic.objects.count()
    topics = Topic.objects.all()[:5]
    context = {'rooms':rooms, 'topics':topics, 'room_count':room_count, 'room_messages':room_messages, 'topics_count':topics_count}
    # messages.info(request, "show some info message")
    return render(request, 'base/home.html', context)


def about(request):
    return render(request, 'base/about.html')

def room(request, pk):
    room = get_object_or_404(Room, id=pk)
    if(room.is_private == False or room.participants.filter(id=request.user.id).exists()):
        form = MessageForm()
        if(request.method == 'POST'):
            body = request.POST.get('msg_body')
            form = MessageForm(request.POST, request.FILES)
            if(form.is_valid() and (not check_empty(body) or request.FILES.get('message_image') is not None)):
                message = form.save(commit=False)
                if(message.message_image != "messages/default.jpg"):
                    message.isImage = True
                    message.body = message.message_image.name
                else:
                    message.isImage = False
                    message.body = body
                message.user = request.user
                message.room = room
                message.save()
                room.participants.add(request.user)
                return redirect('base:room', pk=room.id)
            else:
                messages.error(request, form.errors)

        room_messages = room.message_set.all().order_by('-created')[:10][::-1]
        participants = room.participants.all()
        context = {'has_access':True, 'room':room, 'msgs':room_messages, 'participants':participants, 'form':form}
        return render(request, 'base/room.html', context)
    else:
        if not request.user.is_authenticated:
            messages.info(request, "This room is private you must login to view this")
            return redirect("accounts:login")

        if(request.method == "POST"):
            req , created = Request.objects.get_or_create(
                user = request.user,
                room = room,
            )
        requested = Request.objects.filter(user=request.user, room=room)
        if(requested.exists()):
            requested = True
        else:
            requested = False
        context = {"has_access":False, 'room':room, 'requested':requested}
        return render(request, 'base/room.html', context)

@login_required
def create_room(request):
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room = Room.objects.create(
            host = request.user,
            topic = topic,
            name=request.POST.get('name'),
            description = request.POST.get('description')
        )
        if(request.POST.get('is_private') == 'on'):
            room.is_private = True
        room.save()
        room.participants.add(request.user)
        return redirect('base:home')

    form = RoomForm()
    topics = Topic.objects.all()
    context = {'form': form, 'topics':topics}
    return render(request, 'base/forms/room.html', context)

def update_room(request, pk):
    room = get_object_or_404(Room, id = pk)
    if(request.user != room.host):
        return HttpResponse("Your are not allowed here!")

    form = RoomForm(instance=room)
    if(request.method == 'POST'):
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        room.topic = topic
        if(request.POST.get('is_private') == 'on'):
            room.is_private = True
        room.save()
        return redirect('base:home')
    topics = Topic.objects.all()
    
    context = {'form':form, 'topics':topics, 'room':room}

    return render(request, 'base/forms/room.html', context)    


def delete_room(request, pk):
    room = get_object_or_404(Room, id=pk)
    if(request.user != room.host):
        return HttpResponse("Your are not allowed here!")
    if(request.method == 'POST'):
        room.delete()
        return redirect('base:home')
    
    context = {'obj' :room}
    return render(request, 'base/forms/delete.html',context)


@login_required
def delete_message(request, pk):
    msg = get_object_or_404(Message, id=pk)
    if(request.user  != msg.user):
        return HttpResponse("Your are not allowed here!")
    if(request.method == 'POST'):
        msg.delete()
        return redirect('base:home')
    return render(request, 'base/forms/delete.html', {'obj':msg})



def topics_view(request):


    q = request.GET.get('q') if request.GET.get('q') != None else ""
    topics = Topic.objects.filter(name__icontains = q)
    context = {'topics':topics}

    return render(request, 'base/topics.html', context)


def activity_view(request):
    room_messages = Message.objects.filter(Q(room__is_private=False))
    paginator = Paginator(room_messages, 5)
    page_number = request.GET.get('page')
    room_messages = paginator.get_page(page_number)
    context = {'room_messages':room_messages}
    
    return render(request, 'base/activity.html', context)

def room_requests(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if(room.host != request.user):
        return HttpResponse("You are not Allowed Here")
    

    join_requests = room.request_set.all()
    if request.method == 'POST':
        for req in join_requests:
            if(request.POST.get(req.user.username) == 'Accept'):
                room.participants.add(req.user)
                req.delete()
            elif(request.POST.get(req.user.username) == 'Decline'):
                req.delete()
        return redirect('base:room' , pk=room.id)

    context = {'join_requests':join_requests}
    
    return render(request, 'base/room_requests.html', context)

templates/api_email_template.html
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
    <a href="{{  abs_url  }}">
        Reset Password
    </a>

    
    If the reset link is not clickable please copy this url in your browser {{ abs_url }}
Your username, in case you’ve forgotten: {{ user.get_username }}
    
    Thanks for using our site!

The {{ current_site }} team

templates/base.html
{%  load static  %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %} " type="image/x-icon" />
    <link rel="stylesheet" href="{%  static 'css/style.css'  %}" />
    <title>
        {% block extra_title %}
            Study Buddy
        {% endblock extra_title %}
    </title>
    {% block extra_head %}
        
    {% endblock extra_head %}    
</head>

  <body>
    {%  include 'navbar.html'  %}
    {% block body %}

    {% endblock body %}

    {% block extra_body %}

    {% endblock extra_body %}

    {%  if messages  %}
        <ul class="meassage">
            {%  for msg in  messages  %}
            <div id="snackbar" kk="msg_{{  msg.tags  }}" >{{msg}}
                <svg version="1.1" fill="currentColor" class="messages_from_django_clear_btn" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                </svg>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function(){
                        x.className = x.className.replace("show", "");
                    }, 10000);
                    let messages_from_django_clear_btn = document.querySelector(".messages_from_django_clear_btn");
                    messages_from_django_clear_btn.addEventListener("click", () => {
                        x.className = "";
                    });
                </script>
            {%  endfor  %}
        </ul>

    {%  endif  %}
    <script src="{%  static 'js/script.js'  %}"></script>
  </body>
</html>

templates/navbar.html
{%  load static  %}
<header class="header header--loggedIn">
    <div class="container">
      <a href="/" class="header__logo">
        <img src="{%  static  'images/logo.svg' %} " />
        <h1>StudyBuddy</h1>
      </a>
      <form class="header__search" action="{%  url 'base:home'  %}" method="get">
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          <input type="text" name="q" placeholder="Search for rooms..." />
        </label>
      </form>
      <nav class="header__menu">
        

        <!-- Logged In -->

        
        {%  if request.user.is_authenticated  %}
        <div class="header__user">
          <a href="{%  url 'accounts:profile' request.user.id %}">
            <div class="avatar avatar--medium active">
              <img src="{{  request.user.avatar.url  }}" />
            </div>
            <!-- TODO add firstname lastname below -->
            <p>{{  request.user.username  }} <span>@{{  request.user.username  }}</span></p>
          </a>
          <button class="dropdown-button">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </button>
        </div>
        {%  else  %}

        <!-- Not Logged In -->
         <a href="{%  url 'accounts:login'  %}"> 
          <img src="{%  static 'images/avatar.svg' %}" />
          <p>Login</p>
        </a>

        {%  endif  %}

        <div class="dropdown-menu">
          
          <a href="{%  url 'accounts:logout'  %}" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>sign-out</title>
              <path
                d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
              ></path>
              <path
                d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
              ></path>
            </svg>
            Logout</a
          >
        </div>
      </nav>
    </div>
  </header>