accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = "accounts"

urlpatterns = [

    path('login/', views.login_view, name="login"),
    path('login/<str:from_password_reset>/', views.login_view2, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register_view, name="register"),
    path('update_user/', views.update_user_view, name="update-user"),
    path('profile/<str:pk>/', views.profile_view, name="profile"),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/',views.CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

api/urls.py
from django.urls import path, include
from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Francium API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
   path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   # path('', views.getRoutes),
   path('rooms/', views.RoomListView.as_view()),
   path('rooms/<str:pk>/', views.GetRoomView.as_view()),
   path('create_room/', views.CreateRoomView.as_view()),
   path('room_msgs/<str:pk>/', views.GetMessagesByRoom.as_view()),
   path('send_message/<str:pk>/', views.CreateMessage.as_view()),
   path('room_request/', views.CreateRoomRequest.as_view()),
   path('room_requests/<str:pk>/', views.RoomRequestsView.as_view()),
   path('manage_room_requests/<str:pk>/', views.ManageRoomRequest),
   path('topics/', views.TopicView.as_view()),

   path('accounts/', include('api.accounts.urls')),
]

base/urls.py
from django.urls import path
from . import views
app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('create_room/', views.create_room, name="create-room"),
    path('update_room/<str:pk>/', views.update_room, name='update-room'),
    path('delete_room/<str:pk>/', views.delete_room, name='delete-room'),
    path('delete_message/<str:pk>/', views.delete_message, name='delete-message'),
    path('topics/', views.topics_view, name="topics"),
    path('activity/', views.activity_view, name="activity"),
    path('room_requests/<str:room_id>/', views.room_requests, name="requests"),
]

francium/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

studybud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace="base")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/', include('api.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from base.resize_image import ResizeImageMixin

# Create your models here.

User = get_user_model()

class Topic(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, unique=True)

    def __str__(self) -> str:
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)

    class Meta:
        ordering = ['-updated', '-created']
        
    def __str__(self) -> str:
        return self.name

class Message(models.Model, ResizeImageMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    isImage = models.BooleanField(default=False)
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    message_image = models.ImageField(default="messages/default.jpg", upload_to="messages/", null=True, blank=True)

    def __str__(self) -> str:
        if(len(self.body) > 50):
            return self.body[0:50]
        return self.body

    class Meta:
        ordering = ['-updated', '-created']


class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    request_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-request_time', 'room']
        verbose_name = 'Join request'
    
    def __str__(self) -> str:
        return self.user.username + " requested to join " + self.room.name

    

base/forms.py
from dataclasses import fields
from django.forms import ModelForm
from django import forms
from .models import Room, Message
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']



class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['body', 'message_image']

base/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import  get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from base.models import Request, Room, Topic , Message
from base.forms import MessageForm, RoomForm
from api.custom_validators import check_empty

# Create your views here.

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    rooms = Room.objects.filter(
                Q(topic__name__icontains = q) | 
                Q(name__icontains = q)|
                Q(description__icontains = q)
            ).order_by("-updated")
    room_count = rooms.count()
    paginator = Paginator(rooms, 2)
    page_number = request.GET.get('page')
    rooms = paginator.get_page(page_number)
    room_messages = Message.objects.filter(Q(room__topic__name__icontains = q) & Q(room__is_private=False))[:5]
    topics_count = Topic.objects.count()
    topics = Topic.objects.all()[:5]
    context = {'rooms':rooms, 'topics':topics, 'room_count':room_count, 'room_messages':room_messages, 'topics_count':topics_count}
    # messages.info(request, "show some info message")
    return render(request, 'base/home.html', context)


def about(request):
    return render(request, 'base/about.html')

def room(request, pk):
    room = get_object_or_404(Room, id=pk)
    if(room.is_private == False or room.participants.filter(id=request.user.id).exists()):
        form = MessageForm()
        if(request.method == 'POST'):
            body = request.POST.get('msg_body')
            form = MessageForm(request.POST, request.FILES)
            if(form.is_valid() and (not check_empty(body) or request.FILES.get('message_image') is not None)):
                message = form.save(commit=False)
                if(message.message_image != "messages/default.jpg"):
                    message.isImage = True
                    message.body = message.message_image.name
                else:
                    message.isImage = False
                    message.body = body
                message.user = request.user
                message.room = room
                message.save()
                room.participants.add(request.user)
                return redirect('base:room', pk=room.id)
            else:
                messages.error(request, form.errors)

        room_messages = room.message_set.all().order_by('-created')[:10][::-1]
        participants = room.participants.all()
        context = {'has_access':True, 'room':room, 'msgs':room_messages, 'participants':participants, 'form':form}
        return render(request, 'base/room.html', context)
    else:
        if not request.user.is_authenticated:
            messages.info(request, "This room is private you must login to view this")
            return redirect("accounts:login")

        if(request.method == "POST"):
            req , created = Request.objects.get_or_create(
                user = request.user,
                room = room,
            )
        requested = Request.objects.filter(user=request.user, room=room)
        if(requested.exists()):
            requested = True
        else:
            requested = False
        context = {"has_access":False, 'room':room, 'requested':requested}
        return render(request, 'base/room.html', context)

@login_required
def create_room(request):
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room = Room.objects.create(
            host = request.user,
            topic = topic,
            name=request.POST.get('name'),
            description = request.POST.get('description')
        )
        if(request.POST.get('is_private') == 'on'):
            room.is_private = True
        room.save()
        room.participants.add(request.user)
        return redirect('base:home')

    form = RoomForm()
    topics = Topic.objects.all()
    context = {'form': form, 'topics':topics}
    return render(request, 'base/forms/room.html', context)

def update_room(request, pk):
    room = get_object_or_404(Room, id = pk)
    if(request.user != room.host):
        return HttpResponse("Your are not allowed here!")

    form = RoomForm(instance=room)
    if(request.method == 'POST'):
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        room.topic = topic
        if(request.POST.get('is_private') == 'on'):
            room.is_private = True
        room.save()
        return redirect('base:home')
    topics = Topic.objects.all()
    
    context = {'form':form, 'topics':topics, 'room':room}

    return render(request, 'base/forms/room.html', context)    


def delete_room(request, pk):
    room = get_object_or_404(Room, id=pk)
    if(request.user != room.host):
        return HttpResponse("Your are not allowed here!")
    if(request.method == 'POST'):
        room.delete()
        return redirect('base:home')
    
    context = {'obj' :room}
    return render(request, 'base/forms/delete.html',context)


@login_required
def delete_message(request, pk):
    msg = get_object_or_404(Message, id=pk)
    if(request.user  != msg.user):
        return HttpResponse("Your are not allowed here!")
    if(request.method == 'POST'):
        msg.delete()
        return redirect('base:home')
    return render(request, 'base/forms/delete.html', {'obj':msg})



def topics_view(request):


    q = request.GET.get('q') if request.GET.get('q') != None else ""
    topics = Topic.objects.filter(name__icontains = q)
    context = {'topics':topics}

    return render(request, 'base/topics.html', context)


def activity_view(request):
    room_messages = Message.objects.filter(Q(room__is_private=False))
    paginator = Paginator(room_messages, 5)
    page_number = request.GET.get('page')
    room_messages = paginator.get_page(page_number)
    context = {'room_messages':room_messages}
    
    return render(request, 'base/activity.html', context)

def room_requests(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if(room.host != request.user):
        return HttpResponse("You are not Allowed Here")
    

    join_requests = room.request_set.all()
    if request.method == 'POST':
        for req in join_requests:
            if(request.POST.get(req.user.username) == 'Accept'):
                room.participants.add(req.user)
                req.delete()
            elif(request.POST.get(req.user.username) == 'Decline'):
                req.delete()
        return redirect('base:room' , pk=room.id)

    context = {'join_requests':join_requests}
    
    return render(request, 'base/room_requests.html', context)

base/templates/base/about.html
{%  extends 'base.html'  %}

{% block body %}
    <h1>
        About page
    </h1>
{% endblock body %}

base/templates/base/home.html
{%  extends 'base.html'  %}
{% block extra_head %}

{% endblock extra_head %}

{% block body %}
<main class="layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {%  include 'base/topics_component.html'  %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="mobile-menu">
          <form class="header__search" method="get" action="{%  url 'base:home' %}">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input name='q' placeholder="Search for posts" />
            </label>
          </form>
          <div class="mobile-menuItems">
            <a class="btn btn--main btn--pill" href="{%  url 'base:topics'  %}">Browse Topics</a>
            <a class="btn btn--main btn--pill" href="{%  url 'base:activity'  %}">Recent Activities</a>
          </div>
        </div>
        <div class="roomList__header">
          <div>
            <h2>Study Room</h2>
            <!-- TODO ADD ROOMS TEMPLATE TAG -->
            <p>{{  room_count }} Rooms available</p>
          </div>
          <a class="btn btn--main" href="{%  url 'base:create-room'  %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>add</title>
              <path
                d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
              ></path>
            </svg>
            Create Room
          </a>
        </div>
        {%  include 'base/feed_component.html'  %}   
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {%  include 'base/activity_component.html'  %}
      <!-- Activities End -->
    </div>
  </main>

{% endblock body %}

base/templates/base/room.html
{%  extends 'base.html'  %}
{%  load static  %}
{% block extra_title %}
    {{  room.name  }}
{% endblock extra_title %}

{% block extra_head %}
{% endblock extra_head %}

{% block body %}
<main class="profile-page layout layout--2">
    <div class="container">
      <!-- Room Start --> 
      <div class="room">
        <div class="room__top">
          <div class="room__topLeft">
            <a href="{%  url 'base:home'  %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Study Room</h3>
          </div>

          <div class="room__topRight">
            <a href="{%  url 'base:update-room' room.id  %}">
              <svg
                enable-background="new 0 0 24 24"
                height="32"
                viewBox="0 0 24 24"
                width="32"
                xmlns="http://www.w3.org/2000/svg"
              >
                <title>edit</title>
                <g>
                  <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                </g>
                <g>
                  <g>
                    <path
                      d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                    />
                  </g>
                  <g>
                    <path
                      d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                    />
                  </g>
                </g>
              </svg>
            </a>
            <a href="{%  url 'base:delete-room' room.id  %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>remove</title>
                <path
                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                ></path>
              </svg>
            </a>
          </div>

          <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
          data-edit-url="profile.html">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>ellipsis-horizontal</title>
            <path
              d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
            </path>
            <path
              d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
            </path>
            <path
              d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
            </path>
          </svg>
        </button> -->
        </div>
        <div class="room__box scroll">
          <div class="room__header scroll">
            <div class="room__info">
              <div class="room_name">
                {%  if room.is_private  %}
                <h3>
                  {{room.name }}
                  <svg  class="room_type" fill="currentColor" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g fill="none"><path d="M0 0h24v24H0V0z"/><path d="M0 0h24v24H0V0z" opacity=".87"/></g><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zM9 6c0-1.66 1.34-3 3-3s3 1.34 3 3v2H9V6zm9 14H6V10h12v10zm-6-3c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z"/></svg>              
                </h3>
                
                {%  if room.host == request.user  %}
                <div class="requests_div">
                  <a href="{%  url 'base:requests' room.id %}">
                    <svg class="requests_icon" color="currentColor" id="requests_icon" xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 0 24 24" width="48px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"/></svg>
                  </a>
                  </div>
                  {%  endif  %}
                {%  endif  %} 
              </div>
              <span>{{  room.created|timesince  }} ago</span>
            </div>
            <div class="room__hosted">
              <p>Hosted By</p>
              <a href="{%  url 'accounts:profile' room.host.id %}" class="room__author">
                <div class="avatar avatar--small">
                  <img src="{{  room.host.avatar.url  }}" />
                </div>
                <span>@{{  room.host.username  }}</span>
              </a>
            </div>
            <div class="room__details">
              {{  room.description  }}
            </div>
            <span class="room__topics">{{  room.topic.name  }}</span>
          </div>
          <div class="room__conversation">
            <div class="threads room__messages scroll">
              {% if has_access %}
                {%  for msg in msgs  %}
                    {%  if msg.isImage  %}
                        <div class="thread">
                          <div class="thread__top">
                            <div class="thread__author">
                              <a href="{%  url 'accounts:profile' msg.user.id  %}" class="thread__authorInfo">
                                <div class="avatar avatar--small">
                                  <img src="{{  msg.user.avatar.url  }}" />
                                </div>
                                <span>@{{  msg.user.username  }}</span>
                              </a>
                              <span class="thread__date">{{  msg.created|timesince }} ago</span>
                            </div>
                            {%  if msg.user == request.user  %}
                            <div class="thread__delete">
                              <a href="{%  url 'base:delete-message' msg.id %}">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                  <title>remove</title>
                                  <path
                                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                  ></path>
                                </svg>
                              </a>
                            </div>
                            {%  endif  %}
                          </div>
                          <div class="thread__details">
                            <img style="width: 200px;" src="{{  msg.message_image.url  }}" alt="asdad">
                          </div>
                        </div>
                    {%  else  %}
                        <div class="thread">
                          <div class="thread__top">
                            <div class="thread__author">
                              <a href="{%  url 'accounts:profile' msg.user.id  %}" class="thread__authorInfo">
                                <div class="avatar avatar--small">
                                  <img src="{{  msg.user.avatar.url  }}" />
                                </div>
                                <span>@{{  msg.user.username  }}</span>
                              </a>
                              <span class="thread__date">{{  msg.created|timesince }} ago</span>
                            </div>
                            {%  if msg.user == request.user  %}
                            <div class="thread__delete">
                              <a href="{%  url 'base:delete-message' msg.id %}">
                                
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                  <title>remove</title>
                                  <path
                                  d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                  ></path>
                                </svg>
                              </a>
                            </div>
                            {%  endif  %}
                          </div>
                          <div class="thread__details">{{  msg.body  }}
                          </div>
                        </div>
                    {%  endif  %}
                  {%  endfor  %}
                {%  else  %}
                        {%  if requested  %}
                        <div class="request_form">
                          <input type ="button"  disabled class="btn btn--main" value="Already request sent to room host">
                        </div>
                        {%  else  %}
                          <form class="request_form" action="" method="post">
                            {%  csrf_token  %}
                            <input type="submit" class="btn btn--main" value="Request">
                          </form>
                        {%  endif  %}
                {%  endif  %}
            </div>
          </div>
        </div>
        {%  if has_access  %}
        {%  if request.user.is_authenticated  %}
        <div class="room__message">
            <form  method="POST" action="#" enctype="multipart/form-data">
                {%  csrf_token  %}
                  <input autofocus type="text" class="message_box_input" name="msg_body" placeholder="Write your message here...">
                  <label class="id_message_image" for="id_message_image">
                    <svg class="msg_image_svg" id="msg_settings" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M18 20H4V6h9V4H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2v-9h-2v9zm-7.79-3.17l-1.96-2.36L5.5 18h11l-3.54-4.71zM20 4V1h-2v3h-3c.01.01 0 2 0 2h3v2.99c.01.01 2 0 2 0V6h3V4h-3z"/></svg>
                  </label>
                  {{  form.message_image  }}
                  <div class="msg_properties">
                    <label for="send_msg_btn">
                      <img class="msg_send_icon" src="{%  static 'images/send.png'  %}" />
                    </label>
                    <button type="submit" id="send_msg_btn" hidden></button>
                    <span>  
                      <svg class="msg_clear_svg" width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect width="42" height="4" transform="matrix(0.690405 0.723423 -0.690405 0.723423 3.58317 0.134247)" fill="#C4C4C4"/>
                        <rect width="42" height="4" transform="matrix(0.690405 -0.723423 0.690405 0.723423 0.634251 29.9101)" fill="#C4C4C4"/>
                      </svg>
                    </span>
                    </div>
            </form>
        </div>
        {%  endif  %}
        {%  endif  %}
      </div>
      <!-- Room End -->

      <!--   Start -->
      <div class="participants">
        <h3 class="participants__top">Participants <span>({{  room.participants.count  }})</span></h3>
        <div class="participants__list scroll">
          {% if has_access  %}
            {%  for participant in participants  %}
            <a href="{%  url 'accounts:profile' participant.id  %}" class="participant">
                <div class="avatar avatar--medium">
                    <img src="{{ participant.avatar.url }}" />
                </div>
                <p>
                    @{{  participant.username  }}
                    <span>@{{  participant.username  }}</span>
                </p>
            </a>
            {%  endfor  %}
          {%  endif  %}
        </div>
      </div>
      <!--  End -->
    </div>
</main>
<script src="{%  static 'js/room_functions.js' %}"></script>
{% endblock body %}